export { AssistantPage } from "./assistant/AssistantPage";
export { AudioToTextPage } from "./audio-to-text/AudioToTextPage";
export { ImageGenerationPage } from "./image-generation/ImageGenerationPage";
export { ImageTunningPage } from "./image-generation/ImageTunningPage";
export { OrtographyPage } from "./ortography/OrtographyPage";
export { ProsConsPage } from "./pros-cons/ProsConsPage";
export { ProsConsStreamPage } from "./pros-cons/ProsConsStreamPage";
export { TextToAudioPage } from "./text-to-audio/TextToAudioPage";
export { TranslatePage } from "./translate/TranslatePage";
